# Generated by Django 5.2.6 on 2025-10-07 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('compressive_strength_mpa', models.IntegerField()),
                ('price_per_m3_rub', models.IntegerField()),
                ('image_key', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'concrete_grade',
                'indexes': [models.Index(fields=['grade_code'], name='concrete_gr_grade_c_9cc43e_idx'), models.Index(fields=['status'], name='concrete_gr_status_7a503a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlexuralCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('deleted', 'удалён'), ('formed', 'сформирован'), ('completed', 'завершён'), ('rejected', 'отклонён')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('beam_length_m', models.DecimalField(decimal_places=2, max_digits=6)),
                ('beam_width_mm', models.IntegerField()),
                ('beam_height_mm', models.IntegerField()),
                ('result_max_load_kN', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beam_calculations_created', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beam_calculations_moderated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flexural_calculation',
            },
        ),
        migrations.CreateModel(
            name='FlexuralCalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_index', models.IntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='flexural.flexuralcalculation')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_items', to='flexural.concretegrade')),
            ],
            options={
                'db_table': 'flexural_calculation_item',
            },
        ),
        migrations.AddIndex(
            model_name='flexuralcalculation',
            index=models.Index(fields=['status'], name='flexural_ca_status_f6842d_idx'),
        ),
        migrations.AddConstraint(
            model_name='flexuralcalculation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('creator',), name='uniq_draft_calculation_per_user'),
        ),
        migrations.AddIndex(
            model_name='flexuralcalculationitem',
            index=models.Index(fields=['order_index'], name='flexural_ca_order_i_6cdbe9_idx'),
        ),
        migrations.AddConstraint(
            model_name='flexuralcalculationitem',
            constraint=models.UniqueConstraint(fields=('calculation', 'grade'), name='uniq_calc_grade'),
        ),
    ]
